apiVersion: azure.upbound.io/v1beta1
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "5"
kind: ProviderConfig
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: {{ .Release.Namespace }}
      name: azure-secret
      key: creds