apiVersion: vault.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: vault-provider-config
spec:
  address: http://vault.vault-system:8200
  credentials:
    env: 
      name: VAULT_TOKEN
    # secretRef:
    #   key: credentials
    #   name: vault-creds
    #   namespace: crossplane-system
    source: Secret