apiVersion: v1
kind: Secret
metadata:
  name: vault-creds
  namespace: crossplane-system
type: Opaque
stringData:
  credentials: |
    {
      "token_name": "vault-creds-test-token",
      "token": "123"
    }