apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata: 
  name: network.azure.sergey.dzyuban.com
spec:
  group: azure.sergey.dzyuban.com
  names:
    kind: XNetwork
    plural: xnetwork
  claimNames:
    kind: Network
    plural: network
  defaultCompositionRef:
    name: network.azure.sergey.dzyuban.com
  versions: 
  - name: v1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              version:
                type: string
            required:
              - version
          status:
            type: object
            properties: 
              ips:
                type: string