apiVersion: azure.sergey.dzyuban.com/v1
kind: Network
metadata:
  name: my-network
  labels:
    app: crossplane-example
    chart: crossplane-example-0.1.0
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  version: 1.2.3