apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyter-hub
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: jupyter
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://jupyterhub.github.io/helm-chart/'
    targetRevision: 1.2.0
    chart: jupyterhub
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    # automated: {}
    syncOptions: 
      - CreateNamespace=true