apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: superset
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://apache.github.io/superset'
    targetRevision: 0.3.10
    helm:
      valueFiles:
        - values.yaml
    chart: superset
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: superset
  syncPolicy:
    syncOptions:
      - CreateNamespace=true