apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://airflow-helm.github.io/charts'
    targetRevision: 8.8.0
    helm:
      valueFiles:
        - values.yaml
    chart: airflow
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: airflow
  syncPolicy:
    # automated: {}
    syncOptions:
      - CreateNamespace=true