apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: concourse
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: concourse
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ''
    repoURL: 'https://concourse-charts.storage.googleapis.com/'
    targetRevision: 16.0.0
    chart: concourse
    helm:
      valueFiles:
      - values.yaml
      parameters:
      - name: concourse.web.bindPort
        value: 8090
      - name: concourse.web.service.api.type
        value: LoadBalancer
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions: 
      - CreateNamespace=true