apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: concourse
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: concourse
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://concourse-charts.storage.googleapis.com/'
    targetRevision: 16.0.0
    chart: concourse
    helm:
      parameters:
      - name: concourse.web.bindPort
        value: "8090"
      - name: web.service.api.type
        value: "LoadBalancer"
      - name: web.service.api.loadBalancerIP
        value: "localhost"
  syncPolicy:
    syncOptions: 
      - CreateNamespace=true