apiVersion: secret.example.org/v1alpha1
kind: KipSecret
metadata:
  name: my-kipsecret
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  path: "cloudops/eng/proto/kip1/commData/hub"
  secret: "comm-data-hub"