apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-hashicorp-vault
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: crossplane-secrets-poc
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm/crossplane-hashicorp-vault
    repoURL: https://github.com/SergeyDz/argocd-education
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
  syncPolicy:
    # automated: {}
    syncOptions: 
      - CreateNamespace=true