apiVersion: vault.vault.upbound.io/v1alpha1
kind: Mount
metadata:
  name: vault-creds-kv2
  namespace: default
spec:
  deletionPolicy: Delete
  forProvider:
    path: "secret/kapp"
    type: "kv-v2"
  providerConfigRef:
    name: vault-provider-config