apiVersion: kv.vault.upbound.io/v1alpha1
kind: SecretV2
metadata:
  annotations:
    meta.upbound.io/example-id: kv/v1alpha1/secretv2
  labels:
    testing.upbound.io/example-name: vault-creds
  name: vault-secret-claim
spec:
  forProvider:
    cas: 1
    customMetadata:
      - deleteVersionAfter: 6000
        maxVersions: 99
    dataJsonSecretRef:
      key: connectionString
      name: secret-sample
      namespace: default
    mount: kvv2
    name: kapp
  providerConfigRef:
    name: vault-provider-config