apiVersion: kv.vault.upbound.io/v1alpha1
kind: SecretV2
  name: vault-secret-claim
spec:
  forProvider:
    cas: 1
    customMetadata:
      - deleteVersionAfter: 6000
        maxVersions: 99
    dataJsonSecretRef:
      key: connectionString
      name: secret-sample
      namespace: default
    mount: secret
    name: kapp
  providerConfigRef:
    name: vault-provider-config