apiVersion: generic.vault.upbound.io/v1alpha1
kind: Secret
metadata:
  name: test-vault-claim
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  forProvider:
    dataJsonSecretRef:
      key: credentials
      name: test-vault-claim
      namespace: vault
    path: secret/test-vault
  providerConfigRef:
    name: vault-provider-config