jenkins: 

  controller:
    serviceType: LoadBalancer
    installPlugins: 
      - "kubernetes:3600.v144b_cd192ca_a_"
      - "workflow-aggregator:590.v6a_d052e5a_a_b_5"
      - "git:4.11.3"
      - "configuration-as-code:1429.v09b_044a_c93de"
      - "artifactory:3.17.0"
      - "blueocean:1.25.5"
      - "build-pipeline-plugin:1.5.8"
      - "pipeline-stage-view:2.24"
      - "pipeline-maven:1161.v89a_7dcec5d31"
      - "maven-plugin:3.19"
      - "github:1.34.5"
      - "htmlpublisher:1.30"
      - "sonar:2.14"
      - "pipeline-utility-steps:2.13.0"
      - "build-discarder:60.v1747b0eb632a"