- name: tags-not-found-notification-example
  comment: |
    Tags any secrets missing either the Environment or ResourceOwner tag
  resource: aws.ec2
  filters:
    - "tag:TestNotification": absent
  actions:
    - type: notify
      subject: "Custodian Notification: Test tag is missing"
      violation_desc: "EC2 instance is missing the tag TestNotification"
      action_desc: |
        EC2 instance is missing the tag TestNotification
        Please add the tag TestNotification to the instance
      to:
        - sergey.dzyuban@gmail.com
      transport:
        type: sqs
        queue: https://sqs.us-east-1.amazonaws.com/154563028627/c7n
        role: arn:aws:iam::154563028627:role/c7n-iam-role
        from_address: sergey.dzyuban@gmail.com
        region: us-east-1