- name: ip-address-login-detected
  resource: account
  description: |
    Notifies on all console logins
  mode:
      type: cloudtrail
      role: CloudCustodian-QuickStart
      events:
        - ConsoleLogin
  filters: # regex to match any IP address
      - type: event
        key: 'detail.sourceIPAddress'
        value: |
          ^(\d|[1-9]\d|1\d\d|2([0-4]\d|5[0-5]))\.(\d|[1-9]\d|1\d\d|2([0-4]\d|5[0-5]))\.(\d|[1-9]\d|1\d\d|2([0-4]\d|5[0-5]))\.(\d|[1-9]\d|1\d\d|2([0-4]\d|5[0-5]))$
        op: regex
  actions:
    - type: notify
      template: default.html
      priority_header: 1
      subject: "Login From IP Detected - [custodian {{ account }} - {{ region }}]"
      violation_desc: "A User Has Logged In Externally From A IP Address Outside The Company's Range:"
      action_desc: |
          "Please investigate and revoke the invalid session along
          with any other restrictive actions if appropriate"
      to:
        - sergey.dzyuban@gmail.com
      transport:
        type: sqs
        queue: c7n
        region: us-east-1