apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-patch-and-transform
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-patch-and-transform:v0.5.0

---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-auto-ready
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-auto-ready:v0.2.1

---
