apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xkipsecrets.secret.example.org
  annotations: 
    argocd.argoproj.io/sync-wave: "-4"
spec:
  group: secret.example.org
  names:
    kind: XKipSecret
    plural: xkipsecrets
  claimNames:
    kind: KipSecret
    plural: kipsecrets
  versions:
  - name: v1alpha1
    referenceable: true
    served: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              path:
                type: string  
              secret:
                type: string
                default: secret-sample
            required: 
              - path