apiVersion: v1
kind: Service
metadata:
  name: prometheus-grafana-lb
spec:
  ports:
  - name: service
    port: 8081
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: grafana
  sessionAffinity: None
  type: LoadBalancer