---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
spec:
  service_type: nodeport

  # web_resource_requirements:
  #   requests:
  #     cpu: 200m
  #     memory: 1Gi
  #   limits:
  #     cpu: 200m
  #     memory: 1Gi
  # task_resource_requirements:
  #   requests:
  #     cpu: 200m
  #     memory: 1Gi
  #   limits:
  #     cpu: 200m
  #     memory: 1Gi
  # ee_resource_requirements:
  #   requests:
  #     cpu: 500m
  #     memory: 1Gi
  #   limits:
  #     cpu: 500m
  #     memory: 1Gi