{{- range $scheduledPolicy := .Values.scheduledPolicies }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "cloud-custodian-cron.fullname" $ }}-{{ $scheduledPolicy.name }}"
  labels:
   {{- include "cloud-custodian-cron.labels" $ | nindent 4 }}
data:
  policies.yaml: |-
    policies:
{{- range $path, $_ := $.Files.Glob $scheduledPolicy.policies }} 
{{ tpl ($.Files.Get $path) $ | indent 4}}
{{- end }}
{{- end }}
