apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: gitlab
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://adwerx.github.io/charts'
    targetRevision: 3.4.0
    chart: awx
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions: 
      - CreateNamespace=true