---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-petclinic-app-of-apps
  namespace: argocd
  labels:
    Product: DevOps
    ProductComponents: cicd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd
    repoURL: https://github.com/SergeyDz/spring-petclinic
    targetRevision: feature/jenkins-build
  syncPolicy:
    # automated: {}
    syncOptions: 
      - CreateNamespace=true