image:
  repository: cloudcustodian/c7n
  pullPolicy: IfNotPresent
  tag: main

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # -- Determines whether a service account is created
  create: true
  # -- Optional service account annotations
 
  annotations:
    "eks.amazonaws.com/role-arn": "arn:aws:iam::154563028627:role/c7n-iam-role"

  name: "c7n-service-account"

# -- Optional pod annotations
podAnnotations: {}

# -- Optional pod security context
podSecurityContext: {}

securityContext: {}

scheduledPolicies: 
- name: hourly-policies
  description: Run policies once per hour. For test purposes only it runs every minute.
  concurrencyPolicy: Replace
  schedule: "* * * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  policies: policies/daily/*.yaml
   
- name: weekly-policies
  description: Run policies once per week.
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  schedule: "0 0 * * 0"
  policies: policies/weekly/*.yaml

- name: runtime-policies
  description: Runtime policies will create watch-cloudtrail lambda function to monitor cloudtrail events
  schedule: "* * * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  policies: policies/runtime/*.yaml


# -- Optional resources requests/limits
resources: {}

# -- restartPolicy of CronJob
restartPolicy: Never

# -- Extra environment variables to pass to cloud custodian
envVars: {}

# -- Optional node selector rules
nodeSelector: {}

# -- Optional tolerations to apply to the pod
tolerations: []

# -- Optional affinity rules
affinity: {}

# -- Default custodian args
args:
- "run"
- "-v"
- "-s /home/custodian/output"
- "/home/custodian/policies.yaml"

persistence:
  # -- Persistence volume to save output & cache
  enabled: false
  # -- Persistence volume extra labels
  extraLabels: {}
  # -- Persistence annotations
  annotations: {}
  # -- Persistence existingClaim volume
  existingClaim: ""
  # -- Persistence volume accessMode
  accessMode: ""
  # -- Persistence volume storageSize
  storageSize: "5Gi"
  # -- Persistence storageClassName
  storageClassName: ""

secret:
  # -- Use external secret for custodian instead of using Envars as secrets
  enabled: false
  # -- secretName for custodian
  secretName: ""
  # -- secretName for custodian
  mountPath: /home/custodian/.aws
  # -- secretName readOnly
  readOnly: true
